#CakeStudio - https://dsc.gg/cakestudio

# Настройки плагина
storages:
  #Типы хранилища
  ENDER_CHEST:
    #Звук
    sound: ENTITY_ITEM_PICKUP
    #Запрещенные предметы
    items-filter: [DIAMOND, DIAMOND_ORE]
  SHULKER_BOX:
    sound: BLOCK_NOTE_BLOCK_BASS
    items-filter: [NETHERITE_INGOT, NETHERITE_BLOCK]
  BARREL:
    sound: BLOCK_CHEST_LOCKED
    items-filter: [TNT, GUNPOWDER]

# Сообщения
messages:
  no-permission: "#0EC8E2[✘] &fУ вас нет прав!"
  usage: "&fИспользования: #00F3FB/EnderChestFilter <reload>"
  reload: "#0EC8E2[✔] &fКонфиг успешно перезагружен!"
  unknown: "#0EC8E2[✘] &fТакой команды не существует!"
  player: "#0EC8E2[✘] &fВы не можете #0EC8E2поместить &fэтот предмет в это хранилище!"