#CakeStudio - https://dsc.gg/cakestudio

#Настройки плагина
settings:
  #Типы хранилищ, в которые запрещено помещать запрещенные ресурсы.
  #Доступные значения: CHEST, ENDER_CHEST, SHULKER_BOX, BARREL, HOPPER, DISPENSER, DROPPER и другие
  #Можно указать несколько типов через запятую: [ENDER_CHEST, SHULKER_BOX]
  type: [ENDER_CHEST]
  #Тип звука при попытке поместить предмет в Эндер-Скриню
  sound: ENTITY_ITEM_PICKUP
  #Список предметов для фильтрации
  items-filter: [DIAMOND,DIAMOND_ORE]

#Сообщения
messages:
  no-permission: "#0EC8E2[✘] &fУ вас нет прав!"
  usage: "&fИспользования: #00F3FB/EnderChestFilter <reload>"
  reload: "#0EC8E2[✔] &fКонфиг успешно перезагружен!"
  unknown: "#0EC8E2[✘] &fТакой команды не существует!"
  player: "#0EC8E2[✘] &fВы не можете #0EC8E2поместить &fэтот предмет в Эндер-Скриню!"