# =================================================================
#               CakeEnderChestFilter by CakeStudio
#                    https://dsc.gg/cakestudio
# =================================================================

database:
  type: "sqlite"
  filename: "filters.db"

#Список хранилищ, для которых будет работать фильтр.
#Для каждого хранилища можно указать звук, который будет проигрываться при попытке положить запрещенный предмет.
#Список запрещенных предметов теперь настраивается в игре командой.
storages:
  CHEST:
    sound: BLOCK_CHEST_LOCKED
  ENDER_CHEST:
    sound: ENTITY_ENDERMAN_TELEPORT
  SHULKER_BOX:
    sound: BLOCK_SHULKER_BOX_CLOSE
  BARREL:
    sound: BLOCK_BARREL_CLOSE

messages:
  no-permission: "#C102FA[✘] &fУ вас нет прав для выполнения этой команды."
  reload: "#C102FA[✔] &fКонфиг успешно перезагружен!"
  usage: "#C102FA[!] &fИспользование: &e/EnderChestFilter <type|reload>"
  must-be-player: "&cЭту команду может использовать только игрок."
  must-hold-item: "#C102FA[✘] &fВы должны держать предмет в руке!"
  unknown-storage: "#C102FA[✘] &fХранилище с типом &c%storage% &fне найдено или не поддерживается"
  item-added-to-filter: "#C102FA[✔] &fФильтр для C102FA%item% &fвключен в хранилище C102FA%storage%"
  item-removed-from-filter: "#C102FA[✔] &fФильтр для C102FA%item% &fотключен в хранилище C102FA%storage%"
  player-deny: "#C102FA[✘] &fВы не можете поместить этот предмет в данное хранилище!"